; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.9"

; Profiles
projects[onepagecv][type] = "profile"

; Modules
projects[ctools][version] = "1.0-rc1"

projects[image_url_formatter][version] = "1.0-rc1"

projects[link][version] = "1.0-alpha3"

projects[nodeblock][version] = "1.2"

projects[views][version] = "3.0-rc1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[contact_form_blocks][download][type] = ""
projects[contact_form_blocks][download][url] = ""
projects[contact_form_blocks][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[opcv][download][type] = ""
projects[opcv][download][url] = ""
projects[opcv][type] = "theme"

